# App name
applicationName: helloapp

# Number of replicas
replicaCount: 2

# Docker image info
image:
  repository: myrepo/helloapp
  tag: "1.0.0"
  pullPolicy: IfNotPresent # Other options: Always, Never

# Service info
service:
  port: 8080
  type: ClusterIP

# Resources (CPU/Memory)
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
