apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
